- bin/nrfconnect-scripts.js
- config/eslintrc.json
- config/jest.config.json
- config/webpack.config.js
- mocks/bleDriverMock.js
- mocks/coreMock.js
- mocks/fileMock.js
- mocks/nrfjprogMock.js
- mocks/serialportMock.js
- mocks/styleMock.js
- package.json
- scripts/build.js
- scripts/lint.js
- scripts/test.js
Currently the webpack, jest, and eslint config is duplicated for every app project. If we want to change some common configuration, then we have to do it for every app project. We can improve this by adding common, reusable configuration to pc-nrfconnect-devdep.
When pc-nrfconnect-devdep is installed, it adds an nrfconnect-scripts.js file to node_modules/.bin. This way it can easily be invoked by the app's package.json scripts, like this:
```
"scripts": {
"dev": "nrfconnect-scripts build-watch",
"webpack": "nrfconnect-scripts build-dev",
"build": "nrfconnect-scripts build-prod",
"lint": "nrfconnect-scripts lint lib",
"test": "nrfconnect-scripts test",
"test-watch": "nrfconnect-scripts test --watch",
}
```
With this change the app projects no longer need webpack.config.js, a `jest` section …
> Provide common configuration for app projects

- config/webpack.config.js
Following our internal guidelines of code structure I introduced a function to find the entrypoint of an app modules in a backward compatible manner.
> Added function to webpack config to find entrypoint

- config/eslintrc.json
- config/jest.config.json
- config/webpack.config.js
- mocks/usbMock.js
- package.json
Allows apps to import the usb module that is added by https://github.com/NordicSemiconductor/pc-nrfconnect-core/pull/157.
> Add support for importing the usb module

- bin/nrfconnect-scripts.js
When installing pc-nrfconnect-devdep in other projects, it does sometimes not flatten/dedupe the dependencies in devdep. The dependencies end up in "pc-nrfconnect-devdep/node_modules" instead of
the root node_modules directory. When running f.ex. webpack, it will then not find the dependencies, as it only looks in the root node_modules directory.
To fix this, we can add "pc-nrfconnect-devdep/node_modules" to the `NODE_PATH` environment variable when spawning processes from nrfconnect-scripts.js.
This will fix the issue with webpack and babel-loader, described in https://github.com/NordicSemiconductor/pc-nrfconnect-core/pull/155.
> Add node_modules from devdep to NODE_PATH

- package.json
- scripts/lint.js
The webpack config is set up to do linting of all js and jsx files that it parses. However, `nrfconnect-scripts lint` only performed linting on js files. Now linting jsx files with `nrfconnect-scripts lint` as well.
A fix for this was added in https://github.com/NordicSemiconductor/pc-nrfconnect-core/pull/174. Fixing it here instead, so that all nRF Connect projects will get it.
> Lint both js and jsx when running nrfconnect-scripts lint

- config/webpack.config.js
This PR is due to adding nrf-usb to avoid webpacking usb binaries.
> Add nrf-usb

- config/eslintrc.json
- config/webpack.config.js
- package.json
This PR is due to supporting of including nrf-usb and nrf-device-setup into pc-nrfconnect-core so that apps do not need to have duplicated dependencies.
> Add support for nrf-device-setup and nrf-usb

- config/webpack.config.js
- package.json
Loading resources in apps doesn't work as expected since the app is already _required_ by core, thus URLs are relative to core's dist and not app's dist. `url-loader` seems to fix this issue, for now this is OK for small resources.
> Change file-loader to url-loader for resources, bump version

- .gitignore
- Changelog.md
- README.md
- config/jest.config.json
- config/webpack.config.js
- package.json
- scripts/lint-init.js
This is part of [NCP-2704](https://projecttools.nordicsemi.no/jira/browse/NCP-2704).
Because this may require that other packages using this package have to
be slightly adapted, this is a breaking change.
But please note, that they only can and have to be adapted if they
actually depend on version 4 (or later) of this package. And it is not
necessary, that all packages have to be adapted right away:
E.g. the core/launcher could already use version 4.0 of this package
under the name pc-nrfconnect-shared, while an app may still refer to
version 3.5 of it as pc-nrfconnect-devdep.
> Rename project to pc-nrfconnect-shared

- src/Device/deviceActions.js
This is part of [NCP-2704](https://projecttools.nordicsemi.no/jira/browse/NCP-2704).
The project `pc-nrfconnect-core` was renamed to `pc-nrfconnect-launcher`. This corrects references to the old name (links are redirected but it might still be confusing to keep on using the old name).
> Correct reference to project core/launcher

- Changelog.md
- package.json
- resources/css/error.scss
- src/ErrorDialog/ErrorDialog.jsx
- src/ErrorDialog/ErrorDialog.test.jsx
- src/ErrorDialog/errorDialogActions.js
- src/ErrorDialog/errorDialogReducer.js
This supports [NCP-2674](https://projecttools.nordicsemi.no/jira/browse/NCP-2674) to enhance the error message when a sources file was removed. The main change for that issue is done in the launcher.
This change here enhanced error dialogs:
- Made URLs in error messages clickable (and more generally interpret them as markdown)
- Made error messages selectable again (regression) to enable copy&pasting them.
- Enabled custom error resolutions
> Enhance removed sources handling

- Changelog.md
- package.json
- resources/css/log-entry.scss
- resources/css/log-viewer.scss
- src/Log/LogViewer.jsx
- src/Log/logReducer.js
This PR removes dependency to old and unmaintained react-infinite module in the by a simple reimplementation of the LogViewer component that has reduced limitation of 1000 log entries.
Related PR: https://github.com/NordicSemiconductor/pc-nrfconnect-launcher/pull/401
> Remove dependency to react-infinite

- .huskyrc.json
- Changelog.md
- package.json
- scripts/pre-push.sh
This creates a git hook using [husky](https://github.com/typicode/husky) when running `npm install` that lints and tests the code before pushing it (and aborts the push if there are any error detected).
You can opt out of linting by setting the environment variable `GIT_SKIP_LINT_ON_PUSH` and similar `GIT_SKIP_TEST_ON_PUSH` to skip running the tests. If you want to skip all hooks, you can instead also set the environment variable `HUSKY_SKIP_HOOKS` to `1`, [as described in the husky docs](https://github.com/typicode/husky#skip-all-hooks-rebase).
As you probably are aware, you can also skip running the hooks during a push with the parameter `--no-verify` as in `git push --no-verify`.
> Lint and test before push

- src/Device/DeviceSelectorView.jsx
Part of [NCP-2996](https://projecttools.nordicsemi.no/jira/browse/NCP-2996).
Because this component is not used in old apps, we do not have to remain backward compatible.
Also switch to using the index as key, because the path/comName is not always unique.
> Switch to new serialport property path

- src/App/App.jsx
This PR binds ALT+L keyboard shortcut in the app to opening the Launcher window just as it used to be in legacy apps.
> Add old ALT+L (Option+L) keyboard shortcut to open Launcher window

- Changelog.md
- config/jest.config.json
- package.json
As discovered in switching the boilerplate app to the new architecture, mocking nrf-device-lister and nrf-device-setup was still missing in the jest configuration: https://github.com/NordicSemiconductor/pc-nrfconnect-boilerplate/tree/new-arch
The missing configuration is the reason why this build failed: https://dev.azure.com/NordicSemiconductor/Wayland/_build/results?buildId=4430&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=9c939e41-62c2-5605-5e05-fc3554afc9f5&l=101
> Fix missing mocks

- src/App/App.jsx
- src/Device/DeviceSelector/DeviceSelector.jsx
As described in the [docs](https://nordicsemiconductor.github.io/pc-nrfconnect-docs/api_reference), the properties `appReducer` and `deviceSetup` are optional.
> Weaken proptypes

- package.json
- src/Device/DeviceSelector/DeviceList/AnimatedList.jsx
When a device changes it position in the list (because it is favorited
or the name is changed) it may jump to a different position which is
confusing. So this adds an animation, so that the transition is visually
shown on the screen.
As a bonus it is also now animated when devices are added or removed,
making it easier to see which devices come, go, or stay.
> Make list order changes easier to follow

- Changelog.md
- config/eslintrc.json
- src/About/AboutButton.jsx
- src/About/Section.jsx
- src/App/App.jsx
- src/Device/DeviceSelector/BasicDeviceInfo.jsx
- src/Device/DeviceSelector/DeviceIcon.jsx
- src/Device/DeviceSelector/DeviceSelector.jsx
- src/InlineInput/InlineInput.jsx
- src/Main/Main.jsx
- src/PseudoButton/PseudoButton.jsx
It is too often quite reasonable to not follow the rule, as the examples
show where we had previously disabled it locally. These overrides are
also removed in this commit.
> Disable ESLint rule react/require-default-props

- src/About/about.scss
- src/App/VisibilityBar.jsx
- src/App/visibility-bar.scss
- src/Device/DeviceSelector/DeviceList/device-list.scss
- src/Device/DeviceSelector/DeviceList/edit-device-buttons.scss
- src/Device/DeviceSelector/basic-device-info.scss
- src/Device/DeviceSelector/selector-button.scss
- src/Log/log-header.scss
- src/NavBar/nav-menu-item.scss
- src/variables.scss
Part of [NCP-3117](https://projecttools.nordicsemi.no/jira/browse/NCP-3117).
Several small changes from that issue:
* The pane titles in the navigation bar turn blue on hover. Let them stay grey.
* Roboto thin looks too fragile on some displays, use Roboto light instead.
* Selected device: the serial number should be blue, not grey.
* In the visibility bar, the background of the “show side panel” area has the same colour as the padding in the main view. This looks strange if both side panel and log are hidden. Resolution: Change the background of the “show side panel” area to the background colour of the side panel if the side panel is hidden.
> Small visual redesign changes

- src/Device/DeviceSetup/DeviceSetupView.jsx
- src/Dialog/ConfirmationDialog.jsx
- src/Log/LogHeaderButton.jsx
- src/Logo/Logo.jsx
- src/NavBar/NavBar.jsx
- src/Slider/Handle.jsx
- src/Slider/Slider.jsx
Forgot to do this in the PR #60: Some uses of `defaultProps` were just unnecessary and could be removed. Others could be converted to default function arguments.
> Remove all uses of defaultProps

- Changelog.md
- src/App/App.jsx
- src/App/App.test.jsx
- src/App/appLayout.js
- src/NavBar/NavMenu.jsx
- src/NavBar/NavMenuItem.jsx
This PR is important for any app that maintains objects/state/logic which is created by the components when they get rendered in the main view. Since the About pane is automatically added, even single pane apps are effected by this flaw.
Potential improvement would be to animate the change between panes, maybe to use some-kind of a Carousel component.
> Render all panes

- Changelog.md
- mocks/electronMock.js
- package.json
The remote property is not a function but an object which has several other properties. The most relevant to mock is the require property since this may cause tests to fail if unexpected modules are required in other modules. https://www.electronjs.org/docs/api/remote
The necessity for this fix is currently demonstrated by [a manual override in `AppManagementFilter.test.jsx`](https://github.com/NordicSemiconductor/pc-nrfconnect-launcher/blob/bc2c62be0133bb4e97ab510067c2ed960ef7e3b1/src/launcher/components/AppManagementFilter.test.jsx#L39-L42) without which the test fails.
> Fix remote property on electron mock

- src/App/App.jsx
- src/App/VisibilityBar.jsx
- src/NavBar/NavBar.jsx
Currently, the device selector, sidepanel, and log UI elements are mandatory in the new API, even if they aren't needed. This is the case in the Toolchain Manager, which doesn't use any of them.
This PR:
* Makes the `deviceSelect` and `sidePanel` props optional, only rendering them if they're not `null`
* Introduces a new `showLogByDefault` prop, which determines whether the log will open on application startup or otherwise. It defaults to `true`.
An app with everything turned off will thus look like this:
> Make device selector, sidepanel, and log optional

- Changelog.md
- package.json
- src/Toggle/Toggle.jsx
Should the state of the Toggle component depend on a value that has changed outside of the Toggle itself would end up in a mismatch between the internal state and the external value.
This PR is meant to fix this case.
Additionally the onToggle callback now provides the newly set value.
> Fix the Toggle components state in case it's controlled from outside

- Changelog.md
- package.json
- src/Device/DeviceSelector/DeviceList/MoreDeviceInfo.jsx
- src/Device/DeviceSelector/DeviceList/device-list.scss
- src/Device/DeviceSelector/DeviceList/more-device-info.scss
Three small changes to the device selector, more specifically to the device details:
- Add PCA number
- Remove the wrong line below the port names
- Better alignment for the port names: Port names were centered, which looked okay for long names but out of place for shorter names. If they are short enough, they are now left aligned with the other text
above (device name, serial number, PCA number). If the port names are so
long that they would run to the right out of the device area, then they
port names are moved to the left just enough to fit.
How a device looked before:
How it looks now:
How it looks now with short port names (before they were centred):
> Enhance device selector

- Changelog.md
- package.json
Version 4.8.18 was tagged on GitHub but the version number in `package.json` was not increased. So we need to jump to the next number and release that as 4.8.19.
> Bump version number

- config/prettier.config.js
There was a problem regarding line endings when running Prettier on Windows (LF vs CRLF).
Adding `endOfLine: auto` to the config file fixes this, in line with https://stackoverflow.com/a/53769213/2480017.
> Fix line ending issue with Prettier on Windows

- config/eslintrc.json
Sometimes we need to ignore a typing error; this way we at least have to provide an explanation of why.
> Allow @ts-ignore comments when a description is provided

- Changelog.md
- package.json
- src/App/App.jsx
- src/App/shared.scss
This PR removes outline and box-shadow of focused elements if it was focused by pointer, but not when focus was received by keyboard.
> Use focus-visible polyfill to separate keyboard focus from pointer focus

- Changelog.md
- config/jest.config.json
- config/webpack.config.js
- index.d.ts
- package.json
- src/About/DeviceCard.jsx
- src/Device/DeviceSelector/DeviceIcon.jsx
- src/Device/deviceInfo/deviceInfo.ts
- src/svg.d.ts
Enable showing an own icon and links on the About pane for USB connected devices.
This PR does convert a first file from JavaScript to TypeScript: `deviceInfo`. While most is already prepared for that, the `webpack.config.js` in the launcher still needs two adjustments as described in the `Changelog.md`.
> Enable showing info for USB connected devices

- Changelog.md
- package.json
- src/Device/DeviceSelector/DeviceSelector.jsx
- src/Device/DeviceSelector/useAutoselectDevice.jsx
- src/Device/deviceReducer.js
Enable automatically selecting a specified device when it is detected in an app. To use this, set the environment variable AUTOSELECT_DEVICE, e.g. by running the launcher with
AUTOSELECT_DEVICE=000680407810 npm run app
the device with the serial number 000680407810 is automatically selected when apps using the new architecture see it for the first time. 
When one deselects the device it is not automatically selected again. After restarting the app, the device is automatically selected again.
> Autoselect a device during development

- config/webpack.config.js
Build logs get spammed with warnings because eslint-loader is looking through node_modules and failing to locate files. So split up babel-loader and eslint-loader rules so that we can exclude node_modules correctly.
> Exclude node-modules from eslint-loader to prevent warning bonanza

- Changelog.md
- config/eslintrc.json
- package.json
As per [this issue](https://github.com/airbnb/javascript/issues/2331), there's a recent bug in the AirBnB ESLint package (or somewhere along the crazy dependency web) that is breaking the import/no-cycle rule.
Unfortunately this is breaking our pipelines, so we should disable it for now.
> Disable import/no-cycle ESLint rule

- Changelog.md
- package.json
Should fix the breaking change in a recent ESLint version that stopped our pipelines working.
See https://github.com/airbnb/javascript/issues/2331 for more info.
> Pin eslint-plugin-import version to 2.22.1

- Changelog.md
- config/eslintrc.json
- package.json
Disabling the rule it in 4.14.2 was not effective, the fix from 4.14.3 alone is sufficient.
This basically reverts #121.
> Enable import/no-cycle ESLint rule again

- index.d.ts
Two really small things, do not justify a release or even a changelog entry:
- Typo on `serialPort` (`p` should be small)
- Export interface `Serialport` (because it is needed e.g. in RSSI app)
> Fix small typescript issues

- Changelog.md
- package.json
- src/App/shared.scss
- src/InlineInput/inline-input.scss
- src/Slider/Ticks.jsx
The opacity of disabled elements stacked up when they were nested. E.g.
in the following code the input had the opacity applied twice (making the
opacity squared), so it looked lighter than than supposed:
```jsx
<div className="disabled">This <InlineInput disabled value="doubled"/></div>
```
> Fix: Stacked opacity on nested disabled elements

- Changelog.md
- index.d.ts
- package.json
- src/App/App.jsx
- src/App/VisibilityBar.jsx
- src/App/appLayout.js
- src/Log/LogEntry.jsx
- src/NavBar/NavMenu.jsx
- src/index.js
- At least on macOS (unsure about Linux, is no problem on Win 10) clicking on URLs in the log viewer did not open it in a browser
- In the PPK app we need to query and set the active pane and I think this also already came up in other apps. But this was not possible through an official API yet, so this adds an API for that.
- The `systeminformation` package had a security vulnerability for which @dependabot created #116. This makes that PR obsolete.
> Small fixes

- Changelog.md
- package.json
- src/Device/deviceInfo/deviceInfo.ts
Because the nRF5340 DK superseded the PDK.
> Update nRF5340 links from PDK to DK

- Changelog.md
- index.d.ts
- package.json
- src/App/App.jsx
Not defining an app reducer ([as done in the boilerplate project](https://github.com/NordicSemiconductor/pc-nrfconnect-boilerplate/blob/master/src/index.jsx#L49)) actually led to an error. 🤦
> Fix: Not defining an app reducer led to an error

- Changelog.md
- index.d.ts
- package.json
The TypeScript definition did not specify that pane components can get a property `active`.
> Fix: Missing prop type for pane components

- Changelog.md
- index.d.ts
- src/App/App.jsx
This is part of [NCP-3569](https://projecttools.nordicsemi.no/jira/browse/NCP-3569).
This enables apps to define side panels that can vary by pane, as [described in the Changelog](https://github.com/NordicSemiconductor/pc-nrfconnect-shared/blob/18b81709777c8464d994fe9e65505e2bc96a5fce/Changelog.md#added). 
A very simple demonstration is [the branch `demonstration/sidepanel_per_pane` in PPK](https://github.com/NordicSemiconductor/pc-nrfconnect-ppk/compare/demonstration/sidepanel_per_pane) (requires a launcher that also uses a version of `shared` that incorporates this change).
> Feature: Side panel per pane

- Changelog.md
- index.d.ts
- package.json
- src/App/App.jsx
- src/index.js
- src/utils/persistentStore.ts
This is part of [NCP-3569](https://projecttools.nordicsemi.no/jira/browse/NCP-3569).
https://github.com/NordicSemiconductor/pc-nrfconnect-shared/pull/139/commits/089dc10d3bf83eba2da4b96136f817b75f0b6d59 in #139 previously added the ability to `shared` to read and use the content of the app's `package.json`. This PR uses this for two things: usage data and the persistent store, as described in the changelog:
- Property `reportUsageData` to component App.
- Function `getPersistentStore` to get a persistent store, specific for the
app. The app name from `package.json` is used to identify the app.
- If your app wants to report usage data, you can remove the code to call
`usageData.init()` and instead set the property `reportUsageData` to the
component `App`.
- If your app already use a …
> Use the app's package.json

- Changelog.md
- index.d.ts
- package.json
- scripts/build.js
- src/utils/colors.scss
`$white` and `$black` are also used in some projects, so they are also had to be exported.
Also: When running `npm run webpack` or `npm run build` a build error did not lead to a non zero exit status to signal the error. This was corrected.
> Missing export

- Changelog.md
- package.json
- src/App/appLayout.js
E.g. when an app previously had four panes, it was persisted that the user was
previously on the last pane and a new release of the app has just a single pane
then the app crashes when that user opens the app again.
> Wrong current pane could crash the app.

- Changelog.md
- index.d.ts
- package.json
- `onToggle` is optional. It can be `undefined`, to use the toggle
just for decoration or to show a current value.
- `barToggledColor` was wrong, correct is `barColorToggled`.
- `label` is optional. When `children` are specified the `label` is not
used anyhow. If neither `children` nor a `label` is specified, then
there simply will be no label.
> Fix: Type of Toggle props were slightly wrong

- .gitignore
- azure-pipelines.yml
- package-lock.json
- src/Device/DeviceSetup/DeviceSetupView.jsx
- src/Device/deviceActions.js
- src/Device/deviceReducer.js
- src/PseudoButton/PseudoButton.tsx
- test/testrenderer.jsx
`pc-nrfconnect-shared` is (of course) not an app but used as a library in other projects. My understanding was, that in these cases `package-lock.json` should not be committed. That stems from the fact, that `package-lock.json` is ignored by other packages, that depend on `pc-nrfconnect-shared`.
What I learned now: This is not an undisputed practice. Some advocate for commiting `package-lock.json` also for library packages.
One reason for this, which we now also experienced several times: By not commiting `package-lock.json`, the build is not reproducable anymore, because retrieving and building the package again at a later time may lead to different dependencies being used.
So in this commit I added a `package-lock.json` and change the azure build to use it.
> Add package-lock.json

- package-lock.json
- package.json
- src/ErrorBoundary/ErrorBoundary.jsx
This PR is in preparation for the changes in Launcher which will implement [https://trello.com/c/Ktagc7cB/74-add-error-boundaries-to-launcher-itself](https://trello.com/c/Ktagc7cB/74-add-error-boundaries-to-launcher-itself). 
The changes allow for overriding GA event sending and factory reset / restoring default settings.
> Allow overriding of reporting and factory reset in error boundary

- Changelog.md
- package-lock.json
- package.json
- src/ErrorBoundary/ErrorBoundary.jsx
- src/FactoryReset/FactoryResetButton.jsx
- src/FactoryReset/FactoryResetButton.test.jsx
This implements [https://trello.com/c/li9bqFPm/49-factory-reset-in-the-error-message-about-pane-other-places](https://trello.com/c/li9bqFPm/49-factory-reset-in-the-error-message-about-pane-other-places).
This PR adds a `FactoryResetButton` component. This component provides a confirmation dialog to confirm that a reset should be done. Also users of this component can override the default reset functionality and the confirmation message. This button is also added to the About pane, so users have a handy way of restoring default settings.
> Add new FactoryResetButton component.

- Changelog.md
- package-lock.json
- package.json
- src/Card/Card.tsx
- src/Card/card.module.scss
- src/css.module.d.ts
For https://trello.com/c/IHlj9mlX/119-fix-layout-issue-introduced-for-the-toolchain-manager:
The CSS class name `nrf-card` used in the `Card` component clashed with a likewise class name in the toolchain manager.
To fix the problem but also demonstrate how we can prevent such problems in the future, this commit switches in the `Card` component from traditional CSS class names to [CSS modules](https://github.com/css-modules/css-modules).
If you want to use CSS modules anywhere, the CSS filename needs to include `.module.` and you need to import that CSS file and use its content in your JSX files as you can see in the `Card` component.
> Fix layout breakage

- Changelog.md
- package-lock.json
- package.json
This is a practice [recommended in the prettier
documentation](https://prettier.io/docs/en/install.html). Not doing it
so far led to unwanted behaviour: When updating to any new version of
`pc-nrfconnect-shared` in an app or the launcher, the formatting might
change, even though it is not mentioned in the Changelog.
This could happen, because pc-nrfconnect-shared until this commit
only depended on version `^2.1.1` of prettier. If e.g. a version 2.2.0
of prettier was released, installing any new version of
pc-nrfconnect-shared led to also installing prettier 2.2.0.
> Pin the prettier version to exact version

- Changelog.md
- config/webpack.config.js
- package-lock.json
- package.json
This PR is to add scope for nrf-device-lib-js in webpack.
> Add support for @nordicsemiconductor/nrf-device-lib-js

- Changelog.md
Update [changelog according to our recent discussions](https://nordicsemiconductor.github.io/pc-nrfconnect-docs/changelogs). Also part of https://trello.com/c/KxZ9IhVY/172-display-date-in-the-release-note-for-apps.
> Remove doubled dashes

- Changelog.md
- package-lock.json
- src/App/App.jsx
- src/utils/logLibVersions.ts
In the programmer app we already log the library versions. But this should rather be done here in shared, so that it happens for all apps.
> Log the versions of our low level libraries

- Changelog.md
- src/Device/deviceInfo/deviceInfo.ts
The thingy91 does not display a boardVersion, and therefore it is not
properly mapped to the PCA. This commit implements a soltuion to detect
the thingy91 from the serialNumber instead.
> fix: display thingy91 device name in select device

- config/eslintrc.json
Turn of rule that requires a default export if there is only a single export. No code is expected to be able to break from this change.
> Turn off rule to allow explicit export without default

- src/utils/open.js
The openFile()-method was renamed to openPath() in electron 9 and also made async.
The open log button was affected.
> Use new api-method

- Changelog.md
- bin/nrfconnect-license.mjs
- package.json
- scripts/lint.js
- The license check now ignores all files in `.gitignore` and the folder
`.git`. Before it just ignored `node_modules`, `dist`, and `.git`.
- With `npm run lint` the license check failed to run for shared on Windows.
> Enhance license check

- Changelog.md
- index.d.ts
- package-lock.json
- package.json
- src/About/About.jsx
- src/About/DocumentationCard.jsx
- src/About/documentationSlice.js
- src/About/documentationSlice.ts
- src/App/App.jsx
- src/coreReducers.js
Adds a documentation property to the App component which will show "documentation sections" in the about pane.
An array of objects like these would be passed to the App component:
```
<DocumentationSection
title="Infocenter"
link="https://infocenter.nordicsemi.com/index.jsp?topic=%2Fug_nc_programmer%2FUG%2Fnrf_connect_programmer%2Fncp_introduction.html"
linkLabel="Go to infocenter"
>
For more information about this app and its usage, visit the
infocenter page for it.
</DocumentationSection>
```
> feat: add documentation card in about pane

- Changelog.md
- index.d.ts
- package.json
This lets shared export typings of components using css modules, with the types from the modules themselves.
> Extract typings to avoid apps having to resolve css modules for now.

- Changelog.md
- config/eslintrc.json
- package-lock.json
- package.json
- src/Device/deviceLister.ts
- src/Device/deviceSlice.ts
- src/Device/initPacket.ts
- src/Device/jprogOperations.js
- src/Device/sdfuOperations.js
- src/state.ts
- src/utils/logLibVersions.ts
For https://trello.com/c/8yg4tEWq/341-enumerateworker-error:
Main changes are 0c0281945b91715b161600b1836fc69ab6e44c8d to increase the timeout when enumerating and e956671c5c0b0dacdd0e7a28fac0d110acf6b399 to get better logging when enumerating fails. The rest is more cleanup.
> Make interoperability with device-lib more robust

- Changelog.md
- index.d.ts
- src/Device/deviceLister.ts
- src/Device/deviceSetup.ts
- src/logging/createErrorMessage.test.ts
- src/logging/createErrorMessage.ts
- src/logging/index.ts
- src/utils/logLibVersions.ts
- src/utils/systemReport.ts
In #218 in lots of error logging places the code `error.message` was replaced by `error instanceof Error ? error.message : error`. This altered the behaviour because e.g. device-lib returns error objects which do have a `message` property but are not instances of `Error`.
#233 enhanced the situation by calling `JSON.stringify` in one place but it also means that the whole error object is now dumped as JSON into the log, which may not be so readable.
This PR now wants to mostly restore the initial behaviour and enhance it slightly:
1. A function `logError` on the logger is introduced, so that everywhere where we want to log an error (usually in a `catch` block) we can use the same function.
2. That function handles different kind of situations: 
1. If the error is an instance of `Error`, …
> Enhance error logging

- src/Device/deviceSetup.ts
- src/Device/deviceSlice.ts
- src/state.ts
It seems that apps expect the shared device state to have a device in the deviceInfo property.
> Store device in deviceinfo

- Changelog.md
- src/Device/deviceSetup.ts
- src/Device/jprogOperations.ts
It seems that apps expect the shared device state to have a device in the deviceInfo property.
> Return device even when not programming it

- Changelog.md
- package-lock.json
- package.json
This warning was previously shown, when creating the very first system report using an app in nRF Connect for Desktop on macOS Monterey (the warning was not shown for later system reports): ![MicrosoftTeams-image](https://user-images.githubusercontent.com/260705/142599354-ac3baace-8951-494c-bc89-1068db212e83.png)
[The according issue in `systemreport` was fixed](https://github.com/sebhildebrandt/systeminformation/issues/627) and this PR uses the new version of `systemreport`.
> Fix warning when creating a system report on macOS Monterey

- Changelog.md
- mocks/deviceLibMock.js
- package-lock.json
- package.json
Unit tests that import files that import something from shared currently fail due to a function not beeing mocked out as of now.
> Mock nrf-device-lib-js function

- Changelog.md
- src/App/shared.scss
Especially on the About pane disabled secondary buttons looked strange without a border.
Before:
With this fix:
> Fix secondary disabled buttons

- Changelog.md
- config/eslintrc.json
- package.json
Because there it is often ok to use it and have it fail the test if something is unexpectedly null.
> Allow non null assertion parameter `!` in tests

- Changelog.md
- config/eslintrc.json
- package.json
With this it should be fine to tell ESLint to lint _all_ files, by changing the `lint` script in    `package.json` to `nrfconnect-scripts lint .`. 
If there are more    (e.g. generated) files that need to be ignored during linting, one can    create    [a `.eslintignore` file](https://eslint.org/docs/user-guide/configuring/ignoring-code#the-eslintignore-file)    and add the files to be ignore there in your project.
> Ignore the `/dist` folder while linting

- .renovaterc.json
Starting to use renovate seems a bit tedious because of all the outdated
dependencies. So, I try to first let renovate group all upgrades into a
single PR, test (and hopefully merge) that and after that switch back to
individual PRs.
> Prepare upgrading all packages

- .renovaterc.json
Non-major updates usually do not cause any problems. So we can group them, hoping to spare us a lot of small PRs.
> Renovate: Group all non major updates

- Changelog.md
- config/eslintrc.json
- src/Device/DeviceSelector/DeviceList/AnimatedList.tsx
- src/Device/deviceLister.ts
- src/Device/dfu-cc.ts
- src/Device/jprogOperations.ts
- src/Device/sdfuOperations.ts
- src/ErrorBoundary/ErrorBoundary.tsx
- src/Slider/Handle.tsx
- src/utils/packageJson.ts
- src/utils/systemReport.ts
- src/utils/usageData.ts
Warn if ESLint disable directives (like `eslint-disable` or `eslint-disable-next-line`) are used, even though they are not necessary (anymore). Only a warning is shown when running ESLint, it does not fail with an error. Seems like a failure can only be configured through command line args, not through the config. 
Forbid use of `@ts-ignore`. In most cases `@ts-expect-error` is the better choice.
> Warn about unused ESLint disable directives and forbid `@ts-ignore`

- Changelog.md
- package-lock.json
- package.json
Because we do not need it in `shared` any longer and also not in most of our other projects. If a project still needs it, it can add it as a direct dependency.
> Remove dependency on immutable

- Changelog.md
- package-lock.json
- package.json
- src/About/SupportCard.tsx
- src/App/App.tsx
- src/Device/deviceLibWrapper.test.ts
- src/Device/deviceLibWrapper.ts
- src/Device/deviceLister.ts
- src/Device/jprogOperations.ts
- src/Device/sdfuOperations.ts
- src/Log/logListener.ts
- src/index.ts
- src/utils/describeVersion.ts
- src/utils/logLibVersions.ts
- src/utils/systemReport.ts
Already before `device-lib` changed what it returns from `getModuleVersions`. This was adapted in `src/utils/logLibVersions.ts` but not in `src/utils/systemReport.ts` and `src/Log/logListener.ts`. This is fixed here.
Some additional changes:
- The whole code to retrieve a single module version is now encapsulated in the function `getModuleVersion` which also got unit tests.
- In the system report, the versions of `device-lib` and `device-lib-js` are also included.
- Remove an outdated hack in `src/utils/describeVersion.ts`
- Lower the log level of the `Application data folder` message.
- Bump version number
> Fix getting versions from `device-lib`

- package.json
Oversight in #293: The peer dependency should be to only use electron-store v8 from now on.
> Remove option to use `electron-store` 5

- Changelog.md
- config/tsconfig.json
- config/webpack.config.js
- index.d.ts
- package-lock.json
- package.json
- src/Dropdown/Dropdown.module.scss
- src/utils/appDirs.ts
- src/utils/packageJson.ts
When updating an app to this version, it will bundle shared. This requires the launcher used to also use this version of shared (or newer). This will let us update shared without updating the launcher in the future. 
This will increase the bundle size of the apps, as it bundles in shared.
> Bundle shared with apps

- Changelog.md
- package-lock.json
- package.json
(and also bump `@types/react` to the latest version of 17).
Having `@types/react` as a dev dependency, as before, means that apps would usually pull in the latest version of `@types/react`. But v18 there changed the types, esp. removed the children property. https://reactjs.org/blog/2022/03/08/react-18-upgrade-guide.html#updates-to-typescript-definitions
By making `@types/react` a prod dependency, all apps using this version of shared will now also pull in `@types/react@17`, not `@18`.
> Turn `@types/react` into a prod dependency

- Changelog.md
- package-lock.json
- package.json
- src/Device/DeviceSelector/DeviceSelector.test.tsx
- src/Device/deviceLister.ts
- src/Device/sdfuOperations.ts
And release it as `shared@6.0.2`.
> Update `nrf-device-lib-js` to 0.4.6

- Changelog.md
- package.json
- scripts/check-for-typescript.sh
- scripts/nordic-publish.sh
- scripts/nrfconnect-license.sh
Work around an issue on Windows with running scripts using `env -S` https://github.com/npm/cmd-shim/issues/54
> Fix problems with running scripts under Windows

- Changelog.md
- package.json
- scripts/check-for-typescript.sh
- scripts/nordic-publish.sh
- scripts/nrfconnect-license.sh
Because on Unix systems the scripts are soft linked, we need to resolve that link.
> Fix problems with running scripts under Unix

- Changelog.md
- package.json
- scripts/check-for-typescript.sh
- scripts/nordic-publish.sh
- scripts/nrfconnect-license.sh
Trying to determine the script folder portable is just not worth the effort (e.g. while on some platforms we must supply `readlink` with the `-f` argument, it is not allowed on macOS). Hardcoding the path `./node_modules/pc-nrfconnect-shared/scripts` seems the easiest solution.
> Fix problems with scripts

- .renovaterc.json
Because prettier updates are more likely to break the build, do not group them together with other minor and patch updates.
> Handle prettier separate by renovate

- index.d.ts
- src/index.ts
- test/index.ts
- test/testUtil.ts
Importing testUtils from shared now has to use the path:
```
import { testUtils } from 'pc-nrfconnect-shared/test';
```
The problem with having it in the main index ts, was that it was loaded on starting apps at runtime.
> Move testUtils out of main bundle

- Changelog.md
- index.d.ts
- package.json
- src/App/App.test.tsx
- src/Log/logListener.ts
The bug: When bundling shared with an app, clicking on “open log file” did not open the log but showed an error in the log viewer: “Unable to open log file: Error: Could not find file at path: undefined”. Also, the log file created on disk was always empty.
The cause: If the app bundles shared, then the module `logging/index.ts` exists twice: The one bundled with the launcher and the one bundled with the app. The launcher calls `logger.addFileTransport` on the module bundled with the launcher, so the module scoped variable `logFilePath` is set in that module. When the app then calls the `logger` to log something, this is done on the module bundled with the app, so the module scoped variable `logFilePath` is not set in that module.
The fix: Instead of calling `logger.addFileTransport` from …
> Fix: Logging with bundled apps

- Changelog.md
- package.json
- src/utils/packageJson.ts
When 6.3.0 was used in an app the type checking shows an error that was not possible to fix within the app. The explanation is a bit … complicated and described in `src/utils/packageJson.ts`.
> Fix: Type-checking error when used in apps

- Changelog.md
- package-lock.json
- package.json
- src/ErrorBoundary/ErrorBoundary.test.tsx
- src/utils/persistentStore.ts
- src/utils/systemReport.ts
- src/utils/usageData.ts
Fixes a bug on macOS: The launcher and apps that bundle shared froze a few seconds after launch. 
This was caused by [calling `systeminformation.networkInterfaces()`](https://github.com/NordicSemiconductor/pc-nrfconnect-shared/blob/034b0d73ccb6ad9246c200bedfdbecddc9f6e29d/src/utils/usageData.ts#L53) (because on macOS that [calls `ipconfig getpacket`](https://github.com/sebhildebrandt/systeminformation/blob/69987c5c60ae35ca90e77ff106e1238e26229129/lib/network.js#L624-L637) for every network interface, each call takes about 300 ms, which sums up to 5 s in my case).
The network interfaces are only used to [determine a `clientId` for GA](https://github.com/sebhildebrandt/systeminformation/blob/69987c5c60ae35ca90e77ff106e1238e26229129/lib/network.js#L624-L637). 
This PR instead creates and …
> Fix: macOS freeze

- Changelog.md
- index.d.ts
- src/About/SupportCard.tsx
- src/Device/deviceLibWrapper.ts
- src/Log/logSlice.ts
- src/index.ts
- src/state.ts
- src/utils/persistentStore.ts
Exposes a state selector for the verbose log setting
Also removes `nrfdl` from the verbose code when it is not specific for nRF Device Lib
> feat: add export for verbose log state selector

- Changelog.md
- package.json
- src/App/App.tsx
- src/Device/BrokenDeviceDialog/BrokenDeviceDialog.tsx
- src/Device/BrokenDeviceDialog/broken-device-dialog.scss
- src/Device/BrokenDeviceDialog/brokenDeviceDialogSlice.tsx
- src/Device/DeviceSelector/BasicDeviceInfo.tsx
- src/Device/DeviceSelector/DeviceIcon.tsx
- src/Device/DeviceSelector/DeviceList/BrokenDevice.tsx
- src/Device/DeviceSelector/DeviceList/DeviceList.tsx
- src/Device/DeviceSelector/DeviceList/broken-device.scss
- src/Device/DeviceSelector/device-icon.scss
- src/rootReducer.ts
- src/state.ts
Devices with a broken trait will be unselectable and displayed as such:
Clicking the device element brings up a dialog with the broken trait information received from nrf-device-lib
> Broken trait

- Changelog.md
- index.d.ts
- src/utils/useHotKey.tsx
The old API of `useHotKey()` was broken. Now the old and the new API are supported. Using the old API just triggers a warning on the console.
> Fix: Support legacy `useHotKey()`

- Changelog.md
- package.json
- src/logging/index.ts
`getAppLogDir`was not set at the time of importing logging/index.tsx
which caused the log file to never be created.
> fix: log was never created

- Changelog.md
- src/Device/deviceLibWrapper.ts
- src/utils/logLibVersions.ts
We do not fully support M1 yet, and it is therefore advised to install JLink using Universal Installer for nrfdl to properly work.
E.g. when JLink has been installed using the `64-bit Apple M1 Installer`, then you'll see these warnings in the log:
No warnings should appear if JLink has been installed using Universal Installer.
> Recommend macOS users to use JLink Universal Installer

- Changelog.md
- src/ErrorDialog/errorDialogSlice.test.ts
- test/dispatchTo.ts
The testutil `dispatchTo` always initially dispatches an initialisation    action. This resembles more closely what happens in a normal system and    makes it a tad easier to test the initial state.
> Let `dispatchTo` dispatch an initialisation action

- Changelog.md
- config/jest.config.js
- package-lock.json
- package.json
- src/ErrorBoundary/ErrorBoundary.test.tsx
- test/jestResolver.js
The current version of the package `uuid` doesn't work out of the box with the new version of Jest, as described in https://github.com/microsoft/accessibility-insights-web/pull/5421#issuecomment-1109168149.
I applied the fix using a `resolver`, as mentioned at the end of the above link, from https://github.com/microsoft/accessibility-insights-web/commit/9ad4e618019298d82732d49d00aafb846fb6bac7
This also eases using mocks.
> Update Jest to v29

- Changelog.md
- package.json
- scripts/check-app-properties.ts
- scripts/nordic-publish.ts
Adds a new static checker `scripts/check-app-properties.ts` for some basic app properties:
- `package.json`:
- These properties must be set: `name`, `version`, `description`, `displayName`, `engines.nrfconnect`
- `files` must contain: `resources/*`, `LICENSE`, `dist/`
- `repository.url` should exist (and if it exists, then it must be correct)
- `homepage` should exist
- A `Changelog.md` must exist
- `resources` must contain these files: `icon.svg`, `icon.icns`, `icon.ico`, and `icon.png` 
In `Changelog.md` there is the recommendation, that this script is added to `package.json` so that it gets called automatically when invoking `npm run check`.
The script is also invoked when publishing an app, so that no apps without these properties are deployed.
When publishing to the official source, …
> Feature: Check app properties

- Changelog.md
- package.json
- scripts/check-app-properties.ts
- src/Slider/Slider.tsx
Also some other fixes:
- The type of `values` in `Slider` was too strict. (broken in #424)
- The changelog has some smaller issues.
> Fix: `scripts/nordic-publish.ts` failed when ran in the release pipeline

- Changelog.md
- index.d.ts
- src/InlineInput/NumberInlineInput.tsx
- src/Slider/Handle.tsx
- src/Slider/Slider.test.tsx
- src/Slider/Slider.tsx
- src/Slider/Ticks.tsx
- src/Slider/__snapshots__/Slider.test.tsx.snap
- src/Slider/percentage.ts
- src/Slider/range.ts
- src/Slider/rangeShape.ts
- test/setupTests.ts
I was unhappy about the introduction of so called `explicitRange`s. 
A range like this is easily possible but obviously an error:
```ts
{
min: 3,
max: 6,
explicitRange: [4, 6, 7, 8]
}
```
Initially not clear to me was that also a range like this leads to buggy behaviour:
```ts
{
min: 3,
max: 6,
explicitRange: [3, 3.1, 6]
}
```
That second example is missing appropriate values for the optional properties `step` and `decimals`. 
But, even more important, when specifying explicit values, the other range properties should not really be necessary, because they can be deduced. 
So this PR changes that a range can be _either_ specified by enumerating the values _or_ by specifying the properties `min`, `max`, and optionally `step` and `decimals`. 
This is valid for both components where this …
> Enhance specifying ranges

- Changelog.md
- config/tsconfig.json
- index.d.ts
- package.json
- scripts/nordic-publish.ts
- src/utils/AppTypes.ts
-   Property `apps` in type `SourceJson` became mandatory.
-   Renamed type `AppJson` to `AppInfo`.
-   Renamed property `latest` to `latestVersion` in type `AppInfo`.
-   Exported type `AppVersions` and renamed property `tarball` to `tarballUrl`.
-   Bumped target for TypeScript to `ES2020`.
> Feature: Update meta types

- Changelog.md
- package.json
- src/SidePanel/Group.tsx
- src/SidePanel/group.scss
Old method of importing mdi chevron no longer worked. Updated import and relevant styling.
> Update mdi chevron

- Changelog.md
- package.json
- src/App/App.tsx
- src/ErrorBoundary/ErrorBoundary.tsx
- src/Logo/Logo.tsx
- src/utils/systemReport.ts
- typings/externals.d.ts
- typings/generated/src/ErrorBoundary/ErrorBoundary.d.ts
- typings/generated/src/utils/systemReport.d.ts
The components `ErrorBoundary` and `Logo` were broken when used in the previous way from the launcher.
> Fix: Broken usage of unknown state

- Changelog.md
- package.json
- scripts/installHusky.ts
This was sometimes triggered when installing shared as a dependency with npm@7 or later.
The `prepare` script of `shared` is at least sometimes executed in that case, which failed because it contained `husky install`. That in turn expects a `.git` directory. So now the script first checks if that folders exists (which is only correct if `shared` was cloned for development) and only then executes `husky install`.
> Fix: Error when installing shared as dependency

- Changelog.md
- package.json
- scripts/check-app-properties.ts
Check for `Changelog.md` entry in `files` in `package.json`. We need it in our tarballs and for `npm@7` and later it is not added automatically any longer when running `npm pack`.
Also: Switch to use only major versions of releases of `shared`.
> Fix: Missing changelog file with newer npm versions

- Changelog.md
- src/App/ConnectedToStore.tsx
- src/Device/DeviceSelector/DeviceSelector.tsx
More actions (100 instead of 50) and show some more objects, e.g. Maps and Sets [by serialising them](https://github.com/reduxjs/redux-devtools/blob/bef71f4a0eb7335ee942f25c6a2ca5bf81bff5e5/extension/docs/API/Arguments.md#serialize). When building for production the changes are not effective.
> Better Redux DevTools config

- Changelog.md
- package.json
- src/utils/AppTypes.ts
- typings/generated/src/utils/AppTypes.d.ts
There are situations, where we cannot determine the `shasum` easily, e.g. when an app was installed before we started recording the shasum. For these cases it is easier to treat it generally as optional.
> Make `shasum` property optional

- Changelog.md
- main/index.ts
- package-lock.json
- package.json
- src/OpenApp/openApp.ts
- src/index.ts
- typings/generated/main/index.d.ts
- typings/generated/src/OpenApp/openApp.d.ts
- typings/generated/src/index.d.ts
This PR adds the `openAppWindow` functions in shared, and will be used to a new app from an existing app. E.g. open Serial Terminal from Cellular Monitor, and has to option to include `openAppOptions` with `device` and `serialPortPath`, in order to directly connect to the device and serial port when the app is opened.
> feat: automatic open device and port on 'open:app'

- src/utils/appDirs.ts
- typings/generated/src/utils/appDirs.d.ts
Explicitly add data directories to the global Window interface, in order to make typescript aware that the attributes should exist.
These are the errors after running `npm run check` in pc-nrfconnect-cellularmonitor
Append the relevant attributes to the global `Window` interface.
> fix: properties not on global Window

- config/eslintrc.js
- src/Device/deviceSlice.ts
- src/Dropdown/Dropdown.tsx
- src/utils/useStopwatch.test.tsx
The check is useful most of the times.
`@typescript-eslint/no-unused-vars` was turned off because `no-unused-vars` was already turned off. But this is wrong: `no-unused-vars` was turned off because it is not well suited for TypeScript, by having false positives and false negatives for certain TypeScript structures. So, it is superseded by `@typescript-eslint/no-unused-vars`.
So, this change turns `@typescript-eslint/no-unused-vars` back on.
This also removes the configuration to turn off `no-unused-vars` because that is already done by `plugin:@typescript-eslint/recommended`.
This reverts #539.
> Fix: Reactivate the check for unused variables

- Changelog.md
- scripts/nordic-publish.ts
Added a new option `--create-source` to script `nordic-publish` to create a new source when publishing an app.
When one e.g. runs 
```
npm run nordic-publish -- --source release-test-4.1
``` 
in an app and there is no source with the id `release-test-4.1` on the server yet, it fails. 
Now one can run 
```
npm run nordic-publish -- --source release-test-4.1 --create-source "Release test for 4.1"
``` 
and a source with the id “release-test-4.1” and the name “Release test for 4.1” will automatically be created while publishing the app.
> Feature: Create source on publish

- Changelog.md
- package.json
- scripts/prepare-shared-release.ts
- scripts/release-shared.test.ts
- scripts/release-shared.ts
This adds two scripts, to ease releasing new versions of shared.
Requirement for these scripts: You must have [the GitHub CLI tool `gh`](https://cli.github.com) installed and authenticated it (run `gh auth login`).
The scripts look at the latest release on GitHub and assume the next release number from that.
When you run
```
npm run prepare-shared-release
```
the script will update two things:
- The version number in you local `package.json`
- The heading of the latest entry in `Changelog.md`, but only if it is  `Unreleased` or `36 - Unreleased` (assuming 36 is already the correct  version number)
After this, you will of course still need to commit these changes andmerged them into the main branch.
When you run
```
npm run release-shared -- --dry-run
```
the script checks the latest state …
> Add release scripts

- Changelog.md
- main/index.ts
- package.json
- scripts/esbuild-renderer.js
- src/SerialPort/SerialPort.ts
- src/index.ts
- typings/generated/main/index.d.ts
- typings/generated/src/SerialPort/SerialPort.d.ts
- typings/generated/src/index.d.ts
Typical use case for getOptions is for an app that is trying to connect to a port cannot because the port is claimed with different settings. Then, with getOptions, you'll be able to adapt to the current settings.
> Expose `getOptions` on SerialPort

- Changelog.md
- package.json
- src/Dialog/Dialog.tsx
- src/SerialPort/ConflictingSettingsDialog.tsx
- src/index.ts
- typings/generated/src/SerialPort/ConflictingSettingsDialog.d.ts
- typings/generated/src/index.d.ts
This dialog will immediately be used in Serial Terminal and Cellular Monitor, and will provide more options and information to the user about why the serial port is not immediately connectable with the selected settings.
> Add generic dialog for conflicting serial port settings

- Changelog.md
- package.json
- scripts/prepare-shared-release.ts
- src/utils/persistentStore.ts
- typings/generated/src/utils/persistentStore.d.ts
This is mainly in order to allow apps to use migrations
e.g. from cellularmonitor
```typescript
const store = getPersistentStore<StoreSchema>({
migrations: {
'0.4.5': instance => {
instance.set(TRACE_FORMATS, ['raw', 'tshark']);
},
},
});
```
will run this migration from when the app is release with at least v0.4.5
> Allow persistent store migrations

- Changelog.md
- src/Panes/FeedbackPane.tsx
Headers are now same size as the rest of the text, and buttons are placed in the bottom right corner.
> change: FeedbackPane design header and buttons

- Changelog.md
- package.json
- src/Device/DeviceSelector/DeviceSelector.test.tsx
- src/Device/deviceSetup.ts
- src/Device/jprogOperations.ts
- src/Device/sdfuOperations.ts
- typings/generated/src/Device/deviceSetup.d.ts
- typings/generated/src/Device/jprogOperations.d.ts
- typings/generated/src/Device/sdfuOperations.d.ts
Additionally, the check for if the serialport is available has been removed. This is because this should be up to the app to handle (which is generally being done already).
> feat: move needSerialport check into supportProgrammingMode

- Changelog.md
- package.json
- src/Device/DeviceSelector/DeviceSelector.tsx
- src/Device/deviceSetup.ts
- typings/generated/src/Device/DeviceSelector/DeviceSelector.d.ts
- typings/generated/src/Device/deviceSetup.d.ts
This callback is not being used and is a duplicate of onDeviceDeselected
> feat: remove releaseCurrentDevice callback

- Changelog.md
- package.json
- scripts/esbuild-renderer.js
It's a pretty big package (~700kb) and we already list the related react package as an external.
> feat: list react-dom as an external package

- Changelog.md
- package.json
- src/ErrorDialog/ErrorDialog.tsx
- src/ErrorDialog/error.scss
- src/ErrorDialog/errorDialogSlice.test.ts
- src/ErrorDialog/errorDialogSlice.ts
- src/state.ts
- typings/generated/src/ErrorDialog/errorDialogSlice.d.ts
- typings/generated/src/index.d.ts
- typings/generated/src/state.d.ts
For https://trello.com/c/r6e7BZHe: 
This current error dialog two disadvantages we want to enhance:
- The error dialog can already show multiple error messages at the same time. But it often isn't obvious that there are multiple errors and were one error message ends and the next starts.
- We sometimes want to add technical details to an error which are irrelevant to most users.
This PR addresses both. 
Before the error dialog could look like this:
In this particular case shown in the screenshot, it actually shows two messages: The first one consists of the first two paragraphs and the second message is the third paragraph, starting with “EBUSY”. This is not obvious.
After the PR the error dialog could look like this (clicking on “Show technical details” could e.g. reveal a stacktrace):
> Enhance Redux backed error dialog

- Changelog.md
- package.json
- src/Panes/FeedbackPane.tsx
The link to the nodejs documentation could perhaps confuse more then it was helping the user understand we are collecting the operating system of the OS the app is built for, and not what the user is running.
> Give more user friendly list of info collected

- src/FlashMessage/FlashMessage.tsx
- src/FlashMessage/FlashMessageSlice.ts
- typings/generated/src/FlashMessage/FlashMessageSlice.d.ts
Also remove the prepare in `addNewMessage` reducer, as it is not really needed.
> refactor: extract and rename reducer payload

- src/FlashMessage/FlashMessage.tsx
The app where it was tested had a css file where `.message-container` set the element's position to absolute. This is required in order to make the messages "float" on top of the app layout.
> fix: position was not set to absolute

- Changelog.md
- src/FlashMessage/FlashMessage.tsx
- src/FlashMessage/FlashMessageSlice.ts
- src/FlashMessage/flashMessage.css
- temp.txt
-  Makes the slide-in effect a bit snappier
- Reduces the dismissTime of the utility message `newCopiedFlashMessage` from 12s to 3s.
- Adds the slide-out effect on all flash-messages with a `dismissTime`.
> Slide-out effect and faster effects

- Changelog.md
- src/FlashMessage/FlashMessage.tsx
- src/FlashMessage/flashMessage.css
Even faster (reduced duration) slide-in effect. Also deduce the duration of flash-message-loader from `dismissTime` and `slide-out` duration. Then the loader animation can finish before the message slides-out.
> Faster flash message slide-in effect

- Changelog.md
- package.json
- src/index.ts
- src/utils/useFocusedOnVisible.ts
- typings/generated/src/index.d.ts
- typings/generated/src/utils/useFocusedOnVisible.d.ts
Adds the hook `useFocusedOnVisible` to focus an element when a dialog becomes visible.
You can see it in action in the launcher: https://github.com/NordicSemiconductor/pc-nrfconnect-launcher/blob/ac09b41b7a26dd24aca1dab81b4a3607bf993998/src/launcher/features/sources/AddSourceDialog.tsx#L39 (There a local copy of this hook is still used, because this change wasn't available from shared yet)
> Add hook `useFocusedOnVisible`

- src/App/preflight.scss
This is to avoid having to wrap elements that are to be rewritten to tailwind in an extra div
> feat: use tailwind preflight on current element

- Changelog.md
- package-lock.json
- package.json
- scripts/postinstall.js
- scripts/postinstall.ts
- typings/generated/src/utils/udevInstalled.d.ts
- typings/generated/src/utils/udevInstalled.d.ts.map
Some smaller enhancements.
The changes to the postinstall script are a bit obscured, because I also converted it to TypeScript during the branch. Besides the conversion I also did these three changes to it:
- Generate types only if needed
- Only compile the `nordic-publish` script
- Add logging for each step, so one can see what is done
> Enhance pipeline release to npm

- ipc/MetaFiles.ts
- nrfutil/device/batch.ts
- nrfutil/device/batchTypes.ts
- nrfutil/device/common.ts
- nrfutil/index.ts
- nrfutil/moduleVersion.ts
- nrfutil/sandbox.ts
- nrfutil/sandboxTypes.ts
- src/ErrorBoundary/ErrorBoundary.tsx
- src/logging/sendInitialLogMessages.ts
- src/utils/logLibVersions.ts
- src/utils/systemReport.ts
Some ideas for the `feat/use-nrfutil-device`. 
Some would rather belong to `feat/nrfutil-device-clean` but I thought it is easier to make them on top of `feat/use-nrfutil-device`. Doing them on the former branch would mean that we would afterwards rebase and adjust the latter branch.
This change swapes the last two parameters of `prepareSandbox` because we have an ESLint rule that default parameters must come last. (The rule does not respect optional parameters, which is a shame) But this change will only affect the launcher minimally.
> Suggestions for `feat/use-nrfutil-device`

- scripts/release-shared.ts
Most of the times this works automatically but it doesn't hurt to force this.
> Mark release as latest

- src/App/app.scss
`overflow: overlay` is the reason why scrollbar overlays other content like modals.
Replacing with `overflow: scroll` is fixing this issue https://nordicsemi.atlassian.net/browse/NCD-157
Note: also affects any other areas where scrollbar is used. **If this solution is good to go, same should be applied to every area where scrollbar is used**
> [FIX] Scrollbar overlays modal's content

- Changelog.md
- ipc/MetaFiles.ts
- package.json
- scripts/release-shared.ts
- src/Device/deviceInfo/deviceInfo.ts
- src/Dialog/dialog.scss
-   Optional property `nrfConnectForDesktop.supportedDevices` in `package.json`.    Will for now only be used by the Quickstart app.
-   Output link to where in Azure a release should be created.
-   List items in dialog bodies had the wrong size: They inherited the size from    the document body instead of using the same size as was used in the dialog    in paragraphs.
- Old changelog entry.
> Small changes

- Changelog.md
- package.json
- src/Dialog/Dialog.tsx
This example component
```jsx
<ConfirmationDialog
onConfirm={() => {}}
onCancel={() => {}}
isVisible
>
Test
</ConfirmationDialog>
```
was before rendered like this:
(note the little space between the buttons). Now it looks like this:
> Fix: Spacing in dialog footer

- Changelog.md
- src/InlineInput/InlineInput.tsx
- src/InlineInput/NumberInlineInput.tsx
- src/InlineInput/NumberInputWithDropdown.tsx
- src/index.ts
For now the implementation is quite specific for serial-terminal, but will hopefully evolve and be more generic in the future.
How it works is that when you click on the component, it will work as any other NumberInlineInput component, or if you click the chevron on the right, you will see a list of dropdown items to select from.
The implementation design-wise is equivalent to the Dropdown component.
**Baud Rate** is using the new NumberInputWithDropdown component, and **Data bits** is using the Dropdown component.
You can type in anything you want, but will see that the input is invalid when it is invalid.
When you click the Chevron, you see the list of items to select from. When an item is selected, the input field will immediately be updated to that value.
> Add NumberInputWithDropdown component

- ipc/schema/packageJson.ts
- main/index.ts
- mocks/packageJsonMock.ts
- nrfutil/moduleVersion.ts
- scripts/check-app-properties.ts
- scripts/esbuild.ts
- scripts/nordic-publish.ts
- scripts/release-shared.ts
- src/ErrorBoundary/ErrorBoundary.tsx
- src/Feedback/sendFeedback.ts
- src/utils/appDirs.ts
- src/utils/packageJson.ts
- src/utils/persistentStore.ts
- src/utils/usageData.ts
- src/utils/usageDataMain.ts
- src/utils/usageDataRenderer.ts
- Do not mix default and named exports, instead now have two explicit named exports: `packageJson` and `packageJsonApp`. The former is enough in mos cases, the latter has to be used if especially the package.json of an app is required.
- Unify the required env variables `PACKAGE_JSON_OF_APP` and `PACKAGE_JSON_OF_RENDERER` to be just `PACKAGE_JSON`.
> Rework `packageJson.ts`

- Changelog.md
- ipc/launcherConfig.ts
- main/index.ts
- src/About/ApplicationCard.tsx
- src/App/App.test.tsx
- src/index.ts
- src/logging/sendInitialLogMessages.ts
- src/utils/appDetails.ts
- src/utils/appDirs.ts
- src/utils/launcherConfig.ts
- src/utils/packageJson.ts
- src/utils/usageData.ts
- src/utils/usageDataRenderer.ts
The main change here is to replace the functions `getUserDataDir` and `getAppSource` in `src/utils/appDirs.ts` with code that uses IPC calls instead. One motivation for this being that for me it was too hard to understand how or why the previous code there worked.
One consequence of this is: All functions in `usageData` became async but I assume this is no problem since we never rely on the telemetry data being sent sync (and if this is needed, it could be awaited now).
> Switch some code to IPC calls

- Changelog.md
There is no 4.2.2 and next we plan to release the launcher with the version 4.3.0.
Also: The section `Steps to upgrade when using this package` always comes last, so move that section in one instance.
> Correct launcher version number

- Changelog.md
- src/Dropdown/Dropdown.tsx
Make it so that the DropDownItem type is inferred from the properties passed to the Dropdown component.
Some mocked use case to demonstrate:
```tsx
interface CustomValue {
foo: string;
bar: number;
}
const MyComponent = () => {
const items: readonly DropdownItem<CustomValue>[] = someListOfSorts.map( ... );
return <Dropdown
selectedItem={items[0]}
items={items}
onSelect={ (item) => {
console.log(item.foo) // ✅
console.log(item.bar) // ✅
}} />
};
```
> Make the Dropdown component generic

- Changelog.md
- src/utils/usageDataMain.ts
Looking at the documenation I found it hard to deduce, what `envelope.data.baseData` is supposed to contain. But looking at what is actually in there when `usageData.sendUsageData` is invoked from the main process in preparing an nrfutil sandbox I think that `removeAllMetadata` will be in `envelope.data.baseData.properties` and that the `name` will be in `envelope.data.baseData.name`.
> Fix metadata removal

- Changelog.md
- package.json
- scripts/prepare-shared-release.ts
Changing from the shorter version numbers like `134` to the complete `134.0.0` in the changelog because I am trying to find out whether this keeps renovate from picking up the full changelog.
> Complete version numbers in the changelog

- .npmignore
E.g. in https://unpkg.com/browse/@nordicsemiconductor/pc-nrfconnect-shared@134.0.0/coverage/ one can see that we currently include the coverage report in the package we publish to npm. But we don't want to do that.
> Fix: Coverage should not be in npm package

- Changelog.md
- nrfutil/device/batch.ts
- nrfutil/device/boardController.ts
- nrfutil/device/device.ts
- nrfutil/device/getBoardControllerVersion.ts
- package.json
Added nrfutil-device command wrappers for two board controller related commands:
* boardController() for setting a configuration JSON
* getBoardControllerVersion() for getting the boardcontroller fw version and board revision
> NCD-554 board controller commands

- Changelog.md
- package.json
- src/Dialog/dialog.scss
Error details had a larger font size (16px) than the rest of the body of an error dialog (14px).
Before the fix:
With the fix:
> Fix: Font size of error details

- Changelog.md
- ipc/infrastructure/mainToRenderer.ts
- main/index.ts
- nrfutil/sandbox.ts
When spawning the `nrfutil` process fails in certain ways, an uncaught exception in the main process got thrown. 
The “certain ways” make this a bit    hard to reproduce: On macOS this happened, when the `nrfutil` executable did    not have the executable file mode. Usually this should not happen, because    we set that mode ourselves correctly.
But _when_ it happened (and there are probably more ways that can lead to this) a really ugly native dialog message was shown, because it was not reported back to the launcher as an error. The dialog looked e.g. like this: 
The second change gives the launcher the ability to remove the launcher window from being used in IPC calls. This is especially needed on    shutdown. Otherwise when at that time someone still tries to send IPC    messages to …
> Fix: Unhandled error on some `nrfutil` invocations

- Changelog.md
- nrfutil/sandbox.ts
- package.json
- src/Device/DeviceSelector/DeviceSelector.tsx
- src/Device/deviceLister.ts
- src/ErrorBoundary/ErrorBoundary.test.tsx
- src/ErrorBoundary/ErrorBoundary.tsx
- src/index.ts
- src/telemetry/TelemetrySender.ts
- src/telemetry/TelemetrySenderInMain.ts
- src/telemetry/TelemetrySenderInRenderer.ts
- src/telemetry/telemetry.ts
- src/utils/useHotKey.ts
This PR does several changes postponed in #833 because I didn't want to change the API in that PR. The changes here are not big, mostly just refactorings which mean that apps using the telemetry API of shared will have to change the names with which they call it but usually not a lot more.
This should be reviewed and merged after #833 is merged, because the changes here are based on changes that are done in that PR and also partially on what happened in `main` since then.
> Enhance telemetry API

- src/utils/persistentStore.ts
Downgrading an app would have crashed as it tries to read a string as a number
> fix: change persisted state label for backwards combatibility

- Changelog.md
- scripts/nordic-publish.ts
This removes upload of legacy app info file (e.g. https://developer.nordicsemi.com/.pc-tools/nrfconnect-apps/pc-nrfconnect-rssi) while the new app info files (e.g. https://developer.nordicsemi.com/.pc-tools/nrfconnect-apps/pc-nrfconnect-rssi.json) will continue to be uploaded.
Those legacy files are only used by old versions of the launcher (< 4.0.0). All launcher releases since February 2023 do not use the legacy files but the new ones. Older versions of the launcher probably do not run recent versions of the apps anyhow (e.g. because they require `nrfutil`), so it is fine to not supply those old launcher versions with new app versions.
This PR was previously based on #914, but I now made it independent of it, so this can be merged without that.
> Remove legacy app info file upload

- Changelog.md
- ipc/MetaFiles.ts
- ipc/apps.ts
- package-lock.json
- package.json
- scripts/nordic-publish.ts
Motivation: We use sha sum to calculate if build is updated, but sometimes I'm missing timestamps when same version is released over and over again, ending up testing wrong version of the build.
> Feat: Add publishing date for non-official sources

- src/index.ts
Allows for use of getDevices in applications
Allows for use in applications like Cellular Monitor to allow selection of a terminal serial port that isn't associated with the trace device.
Signed-off-by Jared Wolff <hello@jaredwolff.com>
> Exports getDevices for applications

- Changelog.md
- nrfutil/device/logLibVersions.ts
**What it does?**
Removes "undefined" from the error message
---
Code I don't like much, but it definitely doesn't break existing one :)
> Handle "Failed to get the library versions" if error is undefined

- Changelog.md
- ipc/MetaFiles.ts
- ipc/apps.ts
- nrfutil/device/logLibVersions.ts
- nrfutil/index.ts
- nrfutil/jlinkVersion.test.ts
- nrfutil/jlinkVersion.ts
- nrfutil/moduleVersion.ts
- nrfutil/modules.ts
- nrfutil/sandbox.ts
- nrfutil/sandboxTypes.ts
- nrfutil/version.ts
- package.json
- src/utils/systemReport.ts
Some enhancements to our nrfutil code (triggered by https://nordicsemi.atlassian.net/browse/NCD-1043):
- 6efead4ccecfef96cd22797e632b35e3615f1837 Run `nrfutil self-upgrade` before installing a command.
- 24f22fc62142aec6e068802e6e4659519f176f43 Introduce a discriminated union type for the three different version variants.
- 197e63325ee283c83acda6c9911dcd81577583b2 Restrict out `package.json` schema so that only a single version per nrfutil module can be specified.
- a5d52cc8b4775506711ee96890ac5cdad50032a1 Add an `nrfutil` property to installed apps (will be used in an upcoming change to the launcher).
- a498cbd4856d778920e0c4c8589155794d9f518d Make the property `version` in dependencies optional, reflecting a change since `nrfutil-device` 2.7.
- 20fb73ed2e1d15b75d384dce9655032d23362d9e …
> Enhance nrfutil code

- Changelog.md
- config/jest.config.js
- mocks/applicationinsightsMock.ts
- package-lock.json
- package.json
Reason: hide warning ` ApplicationInsights:Cannot load @azure/core-auth package. This package is required for AAD token authentication. It's likely that your node.js version is not supported by the JS Azure SDK.` from the library caused by jest.requireActual()
> Add mock for appinsights

- .github/workflows/build-app.yml
- .github/workflows/test-shared.yml
No need to pinning this to a specific version, just setting the major version is fine. And especially 4.0.0 seems to have an issue that saving the cache is really slow.
> Update setup-node action

- .github/workflows/build-app.yml
- .github/workflows/release-app.yml
Usually the default should be fine, but in one app I have to use an older version until we make it compatible to the latest node version.
> Allow setting the node version in GitHub Actions

- .github/workflows/build-app.yml
Using `default` doesn't work as expected when invoking the workflow from release-app.yml, so we need to specify the default value this way.
> Fix setting a default node version

- .github/workflows/create-source.yml
- ipc/MetaFiles.ts
- package-lock.json
- package.json
- scripts/create-source.ts
- scripts/nordic-publish.ts
Part of [NCD-795](https://nordicsemi.atlassian.net/browse/NCD-795):
Add script and GitHub Actions workflow to create a source. 
The added description field is not yet used, but the idea is to already maintain it and eventually show it in the launcher.
> Create a new source with script or GitHub action

- Changelog.md
- package.json
- src/Group/Group.tsx
This is for npm to allow the usage of documentationtooltips
Sadly this specific case would override the interaction mouse pointer when hovering over the title
It would also conflict if the "title" is used so that has to be considered
> feat: allow for the group heading to be a reactnode

- Changelog.md
- package-lock.json
- package.json
This will get rid of some warnings concerning `util._extend` in test runs.
> Upgrade systeminformation

- Changelog.md
- scripts/nordic-publish.ts
Part of [NCD-1289](https://nordicsemi.atlassian.net/browse/NCD-1289):
With the changes in https://github.com/NordicSemiconductor/pc-nrfconnect-launcher/pull/1099 the launcher now can handle the simpler URLs, so we should also switch to them when we publish apps.
> Use simpler Artifactory URLs for app metadata

- src/Device/deviceSetup.ts
Added a duplicate log previously which I removed.
Also moved the success log message so it would be called in all cases
> refactor: more consistent onDeviceIsReady log

- Changelog.md
Before `nrfutil-device` 2.7.0, the dependency reported as `nrf-probe-lib` since then it is `nrf-probe`. The code in shared depends on the latter, otherwise a warning is issued.
https://docs.nordicsemi.com/bundle/nrfutil/page/nrfutil-device/CHANGELOG.html#2024-10-22-version-270
Also, usage of `x-read` in #998 requires at least `nrfutil-device` 2.7.16 for for nRF52, nRF53, and nRF91 series devices.
> Fix: Require at least nrfutil-device 2.7.16

- Changelog.md
- ipc/MetaFiles.ts
- ipc/apps.ts
- ipc/schema/packageJson.ts
- nrfutil/index.ts
- nrfutil/moduleVersion.ts
- nrfutil/sandbox.ts
- package.json
- scripts/nordic-publish.ts
Apps must now specify what core version of nrfutil they depend on. This is to ensure that more of the environment the app runs in is locked for an app and future updates, in nrfutil do not break the app unexpectedly.
If an app e.g. specifies that it requires nrfutil core 8.0.0 and nrfutil device 2.9.0, then that sandbox will be created in the path `nrfutil-sandboxes/8.0.0/device/2.9.0`.
If the launcher encounters an old app, which does not specify the core version yet, it will default to using nrfutil core 8.0.0, but use the old path, because those apps expect it there, e.g. `nrfutil-sandboxes/device/2.9.0`.
(On macOS with Apple Silicon there would be an additional segment `arm64/` after `nrfutil-sandboxes/` in those examples)
This is used by …
> Specify core version of nrfutil

- Changelog.md
- package.json
- src/logging/index.ts
This happened when apps use a recent version of logform. In reality only the types changes, but using `Array.isArray` also makes it a bit more expressive and safer.
> Fix type error in logging

- .github/workflows/zoomin-publish.yml
- .github/workflows/zoomin.yml
These workflows are used in apps and the launcher to publish documentation to Zoomin.
Previously the launcher and each app had its own workflow for publishing to Zoomin, now the common parts are extracted here.
> Add shared Zoomin workflows

- .github/workflows/release-app.yml
Part of [NCD-1394](https://nordicsemi.atlassian.net/browse/NCD-1394):
For this, two things are required:
- Have a `doc/mkdocs.yml` file.
- When the release-app workflow is called, specify the `doc_bundle_name` input.
When the app is then release through the GitHub Action, the docs will be automatically published to Zoomin:
- To dev if the source is `latest (internal)`
- To prod if the source is `official (external)`
> Automatically publish docs to Zoomin on release

- .github/workflows/release-app.yml
`hashFiles` does not exist in the context of jobs.<job_id>.if https://docs.github.com/en/actions/reference/contexts-reference#context-availability
So, use another solution to check for the existence of `doc/mkdocs.yml`.
> Fix doc publishing workflow

- Changelog.md
- nrfutil/sandbox.ts
- package.json
The error was introduced in #1003 when `this.log` was passed to the new CollectingResultParser. But because `log` was a regular method, `this` in it pointed to the CollectingResultParser instance, not the NrfutilSandbox instance. So turning `log` into an arrow function fixed the issue.
The error was only triggered when verbose logging was turned on, because only in this case log events were emitted.
> Fix error when verbose logging is turned on

- .github/workflows/build-app.yml
- .github/workflows/release-app.yml
[NCD-1185](https://nordicsemi.atlassian.net/browse/NCD-1185): Automatically create a GitHub release when releasing an app to the source “official (external)”
> Automate GitHub releases for apps

- .github/workflows/release-shared.yml
- Changelog.md
- scripts/check-app-properties.ts
- scripts/check-for-typescript.ts
- scripts/create-source.ts
- scripts/esbuild.ts
- scripts/installHusky.ts
- scripts/is-releasable.ts
- scripts/latest-changelog-entry.ts
- scripts/nordic-publish.ts
- scripts/nrfconnect-license.ts
- scripts/postinstall.ts
- scripts/prepare-shared-release.ts
Another fix for #1034:
Seems like the [shebang `#!/usr/bin/env -S npx tsx` recommended by tsx](https://tsx.is/shell-scripts) doesn't work well enough on Windows.
> Fix: Running build scripts failed on Windows

- .github/workflows/auto-publish-shared.yml
- .github/workflows/release-shared.yml
- .github/workflows/test-shared.yml
- .github/workflows/unpublish-npm-version.yml
- Changelog.md
- README.md
- package.json
- scripts/is-releasable.ts
Implements [NCD-1400](https://nordicsemi.atlassian.net/browse/NCD-1400):
If a new version of shared is ready on main then it is automatically
published by a GitHub Action.
The conditions for “is ready” are:
- Builds correctly
- The package.json has a correct version number (one  more than the last published one)
- There is a correct latest changelog entry
- The latest entry is not empty
- It has the correct version number and today`s date
Even if the `package.json` and `Changelog.md` are not correct, shared will still at least be build.
Also added a script to unpublished a version from npm and described the whole process in `README.md`.
> Automatic shared releasing

- .github/workflows/auto-publish-shared.yml
For [NCD-1400](https://nordicsemi.atlassian.net/browse/NCD-1400):
Fix a bug introduced in #1042: Because in GitHub Actions bash is run with `-e` by default, the script failed if shared is not releasable.
> Fix auto-publish script

- Changelog.md
- ipc/apps.ts
- ipc/sources.ts
- package.json
- src/index.ts
Return value of `getDownloadableApps` has less fields now and some more exports where removed, because they were only needed in the launcher and having them in shared made changes harder in the launcher.
> Remove launcher specific API

- .github/workflows/release-app.yml
Create the GitHub release before releasing to Artifactory.
Rationale: It is more likely that the GitHub release will fail, if by accident a tag was already created. Also, it is easier to remove a wrongly created GitHub release than to remove a wrong release from Artifactory.
> Reorder app release steps

- .github/workflows/release-app.yml
While the documentation suggests that the tag should be the default, we experienced it multiple times that it was the title of the last commit instead. So we now set it explicitly.
> Fix: Always set a title for app github releases
