mocks/coreMock.js, package.json
This pull request is made for adding getAddDir() from core to jest test.
=> Add mock getAddDir

scripts/lint-init.js
This PR is due to copy eslint config file to local project.
=> Copy eslint config

scripts/nordic-publish.js
This PR is due to adding script to publish non-official apps.
=> Internal publish

README.md, azure-pipelines.yml
Lint and run tests automatically for every push.
=> Test automatically on Azure

Changelog.md, package.json, scripts/nordic-publish.js
This PR is to support uploading existing artifact instead of packing first.
=> Update to v4.5.0

src/Device/deviceActions.js, src/Log/logListener.js, src/Slider/Bar.jsx
Suddenly ESLint complaint about `no-multiple-empty-lines` for some files.
=> Fix linting errors

Changelog.md, package.json, src/userData.js
Update google analytics settings.
- Set IP anonymize
- Update account ID
=> Set IP anonymize

src/Device/DeviceSelector/BasicDeviceInfo.jsx, src/Device/DeviceSelector/DeviceList/Device.jsx, src/Device/DeviceSelector/DeviceList/EditDeviceButtons.jsx, src/Device/DeviceSelector/DeviceList/MoreDeviceInfo.jsx, src/Device/DeviceSelector/DeviceList/RenameDevice.jsx, src/Device/DeviceSelector/DeviceList/device.scss, src/Device/DeviceSelector/DeviceList/edit-device-buttons.scss, src/Device/DeviceSelector/DeviceList/more-device-info.scss, src/Device/DeviceSelector/DeviceList/rename-device.scss, src/Device/DeviceSelector/favorite.scss, src/Device/deviceActions.js, src/Device/deviceInfo/deviceInfo.jsx, src/Device/deviceReducer.js, src/InlineInput/InlineInput.jsx, src/InlineInput/NumberInlineInput.jsx, src/InlineInput/inline-input.scss, src/InlineInput/number-inline-input.scss
With these changes, clicking on “Rename device” (or on the device name) lets users rename the device right in the device name.
=> Rename with inline input

src/Slider/slider.scss, src/bleChannels.js, src/colors.js, src/logging/consoleTransport.js, src/variables.scss
Part of [NCP-3117](https://projecttools.nordicsemi.no/jira/browse/NCP-3117), this belongs together with NordicSemiconductor/pc-nrfconnect-rssi#57.
* Sliders: On hover the handle enlarges and changes it's colour. Size change should stay but no colour change.
* Incorporate some code, that was previously in the RSSI app
=> Sidepanel redesign updates

src/bleChannels.js, src/index.js
Following [the discussion in PR #64](https://github.com/NordicSemiconductor/pc-nrfconnect-shared/pull/64#discussion_r458570151) I changed the API slightly and adapted the usage in the RSSI app, which indeed is better this way.
=> Make bleChannels API easier to understand and use

Changelog.md, package.json, src/InlineInput/NumberInlineInput.jsx, src/Slider/percentage.js, src/Slider/rangeShape.js
- Added optional chars prop to define number of characters of NumberInput
- Added optional decimals prop to range of Slider
=> Finer slider

Changelog.md, package.json, src/InlineInput/InlineInput.jsx, src/InlineInput/NumberInlineInput.jsx
This PR adds optional onChangeComplete callback to (Number)InputLine components.
=> Added onChangeComplete to InlineInput and NumberInlineInput

src/Device/DeviceSelector/basic-device-info.scss
This PR fixes the selector width on Linux.
=> Fix selector width on Linux

Changelog.md
Describe what steps are needed, when an app (or the launcher) is upgraded to (or over) a new version of shared.
=> Describe steps to upgrade when using shared

Changelog.md, config/tsconfig.json, index.d.ts, package.json, scripts/lint.js, tsconfig.json
The changes are explained in the [Changelog for 4.9.0](https://github.com/NordicSemiconductor/pc-nrfconnect-shared/blob/ee71be2cc4da7a2210cac2a687073b8e2ebdb1b3/Changelog.md#version-490).
=> Enhance TypeScript support

Changelog.md, index.d.ts, package.json
- id and onChangeComplete on Slider are optional
- NumberInlineInput was missing
- The props on the colors record are all of type string
=> Fixed some types

Changelog.md, package.json, src/userData.js
This PR is to update how client id is generated for usage statistics.
=> Update client id generation for usage statistics

src/userData.js
Fix the logic of generating client id.
=> Update the logic of generating client id

Changelog.md, scripts/nordic-publish.js
This PR is to fix fail to upload changelog.
=> Fixed upload script

Changelog.md, src/Device/deviceInfo/deviceInfo.ts
No urgent change, so I do not want to create a release just for this.
=> Add links for PPK2

src/About/about.scss, src/Card/card.module.scss
This PR will change css of card component to make it more usable multiple places
=> Change card scss

Changelog.md, package-lock.json, package.json, src/variables.scss
This PR will change the tooltip background color and opacity
=> Change styling on tooltip

Changelog.md, index.d.ts, package-lock.json, package.json, src/Device/deviceInfo/deviceInfo.ts, src/index.js
Needed the deviceInfo  in cellular monitor. Also corrected a typing of a device property.
=> Expose deviceinfo

Changelog.md, index.d.ts, src/StateSelector/StateSelector.jsx, src/StateSelector/state-selector.scss, src/index.js
Component can be tested here: https://github.com/NordicSemiconductor/pc-nrfconnect-dtm/tree/test/state-selector
=> Add StateSelector component

src/utils/logLibVersions.ts
This code can handle the current buggy versions of nrf-device-lib-js
or also if they are according to their types. It also eliminates the
need for `any`.
=> A more robust variant to fix/version-log

Changelog.md, index.d.ts, package.json, src/Alert/Alert.module.scss, src/Alert/Alert.tsx, src/index.js
=> Create alert component

Changelog.md, package-lock.json, package.json, src/ErrorBoundary/ErrorBoundary.test.jsx
Also had to update a failing unit test.
=> Upgrade nrfdl

Changelog.md, index.d.ts, package-lock.json, package.json, src/index.ts, src/utils/truncateMiddle.test.ts, src/utils/truncateMiddle.ts
Moving this into shared from Cellular Monitor and Programmer.
=> Add convenience function for truncating strings

Changelog.md, src/InlineInput/InlineInput.tsx
Signed-off-by: Pascal Pickel <Pascal.Pickel@nordicsemi.no>
=> style: add inline input margin for mac

Changelog.md, package.json
Because the changes are not only bug fixes. And I forgot to bump the version in package.json anyhow. ¯\\\_(ツ)\_/¯
=> Bump minor version

Changelog.md, package-lock.json, package.json, src/Device/deviceInfo/deviceInfo.ts
Also update `nrf-device-lib-js` to `0.4.8`.
=> Add links for Audio Kit

.husky/pre-push, .huskyrc.json, Changelog.md, config/tsconfig.json, package-lock.json, package.json, scripts/check-for-typescript.sh, scripts/check-for-typescript.ts, scripts/nordic-publish.sh, scripts/nordic-publish.ts, scripts/nrfconnect-license.sh, scripts/nrfconnect-license.ts, scripts/pre-push.sh
Also upgrades husky to the latest version, making some manual steps necessary, see the `Changelog.md` for instructions.
=> Fix on Windows without bash

Changelog.md, config/eslintrc.js, config/webpack.config.js, package-lock.json, package.json, scripts/nordic-publish.js, scripts/nrfconnect-license.ts
In order to use this, when upgrading shared in an app, replace the publish script like this:
`"nordic-publish": "./dist/nordic-publish.js",`
=> Bundle publish script

scripts/nordic-publish.ts
Preparing adding new features in https://trello.com/c/Pilrty2t.
=> Refactor `nordic-publish.ts`

Changelog.md, package-lock.json, src/StateSelector/StateSelector.tsx
Due to no variant being set, bootstrap overwrites our styles with the primary colours.
=> style: use white as selected colour for state selector component

Changelog.md, scripts/nordic-publish.ts
`scripts/nordic-publish.js` now also uploads the SVG icon and updates the new meta files. Using this will be mandatory for the next launcher release.
=> Feature: Support new concept on publish

scripts/nordic-publish.ts
Report more errors that caused problems and also a potentially problematic content of `source.json`.
=> Enhance error reporting in publish script

Changelog.md, index.d.ts, package.json, scripts/check-app-properties.ts, scripts/nordic-publish.ts, src/utils/AppTypes.ts, src/utils/packageJson.ts, src/utils/usageData.ts
Export types `SourceJson` and `AppJson`, describing the structure of the new    meta data files.
=> Export app types

Changelog.md, package-lock.json, package.json, scripts/esbuild-renderer.js
Reverts NordicSemiconductor/pc-nrfconnect-shared#451
=> Revert "Remove react external"

Changelog.md, package.json, src/Device/sdfuOperations.ts
making an unused file in a read only folder.
=> Programming dfu on mac failed due to

Changelog.md, package-lock.json, package.json, src/OpenApp/openApp.ts
The import seem to work functionally, but breaks tests when the project is imported in pc-nrfconnect-launcher.
=> fix: wrong import

Changelog.md, src/App/appLayout.ts, src/NavBar/NavMenu.tsx, typings/generated/src/App/appLayout.d.ts
Also adds a symmetrical navigation, by adding hotkey to switch the next pane to the left.
=> Fix: app crashed when hotkey was used

Changelog.md, src/Alert/Alert.module.scss
Reverts NordicSemiconductor/pc-nrfconnect-shared#542
=> Revert "style: set alert margin-bottom to 8px"

src/Stepper/Stepper.tsx, src/Stepper/stepper.scss
Trying to style according to the sketches
=> Style steppers like the sketches

Changelog.md, package-lock.json, package.json, src/Device/deviceLibWrapper.ts, src/Device/deviceLister.ts, src/state.ts, typings/generated/src/Device/deviceLibWrapper.d.ts, typings/generated/src/state.d.ts
Serialnumber is now optional from device-lib, make the wrapper set a fallback value.
=> Use newer device lib

Changelog.md, src/App/App.tsx
I couldn't find it used in any other app
=> feat: remove support for legacy panes

Changelog.md, package-lock.json, package.json, src/App/App.tsx, src/FlashMessage/FlashMessage.tsx, src/FlashMessage/FlashMessageSlice.ts, src/FlashMessage/flashMessage.css, src/index.ts, src/store.ts, typings/generated/src/FlashMessage/FlashMessage.d.ts, typings/generated/src/FlashMessage/FlashMessageSlice.d.ts, typings/generated/src/index.d.ts, typings/generated/src/store.d.ts
In order to use flash messages, add the <FlashMessages /> component in the app. In order to emit a flash message call one of the relevant thunk functions exported from `flashMessageSlice.ts`.
For MDI icons convenience.
-  "@mdi/js": "^7.2.96"
- "@mdi/react": "^1.6.1"
=> feat: Flash Messages

Changelog.md, package.json, src/utils/usageData.ts
Also removed initialized boolean as it didn't seem relevant enough for just this file
=> fix: handle usage data not initialized

nrfutil/device/batch.ts, nrfutil/device/device.ts, nrfutil/device/getBoardControllerConfig.ts
Add commands to read config from board controller firmware
=> NCD-613: BCTL Add getBoardControllerConfig nrfutil commands

.github/workflows/labels.yml
=> ci: require ui labels also

src/Device/DeviceSelector/DeviceSelector.tsx
Motivation: saw such wording while removing this from serial terminal. Wording there looks better.
No version update or changelog entry cuz this is too minor.
=> Update wording for device selection

nrfutil/moduleVersion.ts, nrfutil/modules.ts, nrfutil/sandbox.ts, package-lock.json, src/About/SupportCard.tsx, src/Device/DeviceSelector/DeviceList/DeviceList.tsx, src/Device/DeviceSelector/DeviceSelector.test.tsx, src/Device/DeviceSelector/DeviceSelector.tsx, src/Device/deviceLister.ts, src/Device/deviceSetup.ts, src/Device/jprogOperations.ts, src/Device/sdfuOperations.ts, src/Log/logSlice.ts, src/SerialPort/ConflictingSettingsDialog.tsx, src/logging/index.ts, src/utils/persistentStore.ts, src/utils/systemReport.ts
Edited tooltips for style and typos.
=> tooltips: review for style and typos

Changelog.md, package.json, src/Device/DeviceSelector/DeviceList/DeviceList.tsx, src/Device/DeviceSelector/DeviceList/VirtualDevices.tsx, src/Device/DeviceSelector/DeviceList/device-list.scss, src/Device/DeviceSelector/DeviceSelector.tsx, src/Device/DeviceSelector/DisconnectDevice.tsx, src/Device/DeviceSelector/SelectedDevice.tsx, src/Device/DeviceSelector/SelectedVirtualDevice.tsx, src/Device/deviceSlice.ts
Still requires hover text change for top left button
=> feat: add offline devices

Changelog.md, scripts/nordic-publish.ts
Part of [NCD-795](https://nordicsemi.atlassian.net/browse/NCD-795):
Extend `scripts/nordic-publish.ts` so that it now allows publishing either (as before) to FTP or instead to Artifactory.
=> Add publishing to Artifactory

src/Device/BrokenDeviceDialog/BrokenDeviceDialog.tsx
=> refactor: use internal error dialog

Changelog.md, config/jest.config.js, package-lock.json, package.json
https://nordicsemi.atlassian.net/browse/NCD-1174
=> Removing mocks for unused packages 

.github/workflows/auto-publish-shared.yml
For [NCD-1400](https://nordicsemi.atlassian.net/browse/NCD-1400):
Fix a bug introduced in #1042.
=> Fix failing npm publishing

Changelog.md, nrfutil/device/logLibVersions.ts, nrfutil/sandbox.ts, nrfutil/version/jlinkVersion.test.ts, nrfutil/version/jlinkVersion.ts, src/Device/deviceLister.ts, src/utils/systemReport.ts
Also changed nrfutil to nRF Util when referring to the entire tool. Changed `nrfutil-<command>` to `nrfutil <command>`.
=> doc: changed JLink to SEGGER J-Link
